# Utiliser une image de base PHP avec Apache
FROM php:8.2-apache

# Installer les extensions PHP nécessaires pour Symfony et PostgreSQL
RUN apt-get update && apt-get install -y \
    libpq-dev \
    unzip \
    git \
    && docker-php-ext-install pdo pdo_pgsql

# Activer le module Apache mod_rewrite pour Symfony
RUN a2enmod rewrite

# Copier les fichiers de l'application Symfony dans le répertoire de travail
COPY . /var/www/html

# Définir le répertoire de travail
WORKDIR /var/www/html

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Installer les dépendances Symfony
RUN composer install --no-dev --optimize-autoloader

# Donner les droits nécessaires pour l'application
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Exposer le port sur lequel Apache écoute
EXPOSE 80

# Lancer Apache en arrière-plan
CMD ["apache2-foreground"]
